# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-14 07:33
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.management import call_command


class Migration(migrations.Migration):

    def load_scope_definition(apps, schema_editor):
        call_command("loaddata", "embeddings.json")

    dependencies = [
        ('content', '0033_content_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNodeEmbedding',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('embedding', models.TextField()),
            ],
        ),
        migrations.RunPython(load_scope_definition)
    ]


