# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-14 07:51
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_scope_definition(apps, schema_editor):
    call_command("loaddata", "embeddings.json")

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_contentnodeembedding'),
    ]

    operations = [
        migrations.RunPython(load_scope_definition)
    ]
