# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-14 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_add_learner_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesettings',
            name='language_id',
            field=models.CharField(blank=True, default='de', max_length=15, null=True),
        ),
    ]
